meson: Still some bug
ImportError: cannot import name 'fastcpp' from partially initialized
module 'transportProp' (most likely due to a circular import)